---
title: "Lessons learnt from transforming SALURBAL data into FAIR data"
subtitle: "A brief guide if you are developing a new dataset and its documentation to ensure your data is FAIR"
author: "Diana Higuera-Mendieta"
date: "2023-01-18"
update:"2023-01-25"
---

1. Context of why we are doing this
2. How FAIR data should be 
3. Naming variables following certain rules. 
4. Have the same fields in the documentation than in the tables 
5. Ensure codebooks have all the information needed
6- Think of strata since the begining

The whole purpose of this blog entry is to make sure no extra work is needed when
developing harmonized datasets with FAIR principles. Currently SALURBAL has invested
several resources and labor in constructing reproducible documentation that allows 
from a traditional standpoint to use harmonized datasets for Latin America. 
However, in the process of building am open data repository 

Right now - Things that should not happen: 
1. Record all the changes done in the procedures and change templates accordingly
- This is important because as the process advances a lot of changes were done 
and while one of us can face a challenge and solve it the other person might not know about it

-Templates in salurbal-fair-renovations-documents-templates is not updated with all the fields
- Define from the begining the skills required for advancing on the steps to get FAIR data
        - Coding skills?
        - Data management experience?
        


FAIR data is important because it ensures thattype  data is Findable, Accessible, Interoperable, and Reusable. This means that data is properly labeled, described, and indexed so that it can be easily discovered and accessed by those who need it. Additionally, FAIR data is designed to be interoperable with other data sources, allowing for greater integration and analysis.

Making data FAIR also promotes transparency and reproducibility in research. When data is easily accessible and understandable, other researchers can verify and build upon previous work. This helps to ensure that scientific findings are robust and reliable.

Furthermore, FAIR data also promotes data reuse by making data available for multiple purposes, increasing the value of the data. This is particularly important in today's data-driven society, where data is increasingly being used to drive decision making and innovation. By making data FAIR, organizations can maximize the value of their data by making it available for use in a wide range of applications.

In summary, FAIR data is important because it ensures that data is properly labeled, described, and indexed so that it can be easily discovered and accessed by those who need it. Additionally, it promotes transparency and reproducibility in research and data reuse, thus increasing the value of the data. It is important for organizations to adopt FAIR data principles to maximize the value of their data.

