project:
  type: website

website:
  image: 'uhc.png'
  favicon: 'favicon.png'
  repo-url: https://github.com/Drexel-UHC/salurbal-project-dashboard
  repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    background: light
    logo: logo.png
    logo-alt: 'SALURBAL logo.'
    collapse-below: lg
    left:
      - text: 'Overview'
        href: index.qmd
      - text: 'FAIR Implementation'
        href: pages/fair/index.qmd
      # - text: 'Renovation manuals'
      #   href: pages/manuals/index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: 'Database'
        href: pages/database/qc.qmd
    right:
      - icon: twitter
        href: https://twitter.com/LACUrbanHealth
        aria-label: SALURBAL Twitter
      - icon: github
        href: https://github.com/Drexel-UHC/salurbal-project-dashboard
        aria-label: SALURBAL GitHub

  page-footer:
    center:
      - icon: twitter
        href: https://twitter.com/LACUrbanHealth
        aria-label: SALURBAL Twitter
      - icon: github
        href: https://github.com/Drexel-UHC/salurbal-project-dashboard
        aria-label: SALURBAL GitHub

  sidebar:
    - collapse-level: 2
    - id: fair
      contents:
        - text: 'FAIR Principles'
          href: pages/fair/index.qmd
        - section: 'Findable'
          contents:
            - text: 'Overview'
              href: pages/fair/findable-overview.qmd
            - text: 'F1. Globally unique and persistent Identifiers'
              href: pages/fair/findable-f1.qmd
            - text: 'F2. Comprehensive metadata'
              href: pages/fair/findable-f2.qmd
            - text: 'F3. Metadata linkable to data'
              href: pages/fair/findable-f3.qmd
            - text: 'F4. Searchable resource'
              href: pages/fair/findable-f4.qmd
        - text: 'Accessible'
          href: pages/fair/accessible.qmd
        - text: 'Interoperable'
          href: pages/fair/interoperable.qmd
        - text: 'Reusable'
          href: pages/fair/reusable.qmd
    - id: manuals
      collapse-level: 2
      contents:
        - text: 'Renovation Overview'
          href: pages/manuals/index.qmd
        - text: 'Step 1: assign var_name'
          href: pages/manuals/step1.qmd
        - text: 'Step 2: summarize strata information'
          href: pages/manuals/step2.qmd
        - text: 'Step 3: evaluate metadata linkage'
          href: pages/manuals/step3.qmd
        - text: 'Step 4: renovate codebooks'
          href: pages/manuals/step4.qmd
        - text: 'Step 5: renovate data'
          href: pages/manuals/step5.qmd
format:
  html:
    toc: true
    theme:
      light: [morph, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css

freeze: true
