---
title: "Accessible"
subtitle: "A1: (Meta)data are retrievable by their identifier using a standardised communications protocol. The protocol is open, free, and universally implementable.`"
pagetitle: "SALURBAL - Accessible"
---

## A1.1

> A1.1 The protocol is open, free, and universally implementable.

We use HTTPS to faciliate data transfer. There are two main ways for users to download data: 1) each variable's web page contains download links for data and associated metadata 2)  users and create a custom data extract on the data portal and have the data/metadata operationalied into a analytical bundle that is then emailed to them. 


## A1.2

> A1.2 The protocol allows for an authentication and authorisation procedure, where necessary.

We deploy the data portal via the Azure Static Web Application Service. This service has built in authentication via OAuth integrating with GitHub or Outlook for handle user authentication. We then write authorisation logic as need in our front-end Next.js application to control information flow. Although this mechanism was developed, we do use it to primarily track user behavior. 

SALURBAL data is stored on an private encrypted server hosted by Drexel University. Data items that which have contractual restrictions remain on this private encrypted server. Data items that are open to the public are then stored within Azure Blob Storage with anynyous access (anyone can have access to them). 

## A2

>A2  Metadata are accessible, even when the data are no longer available.

We plan to submit and metadata to ICPSR. Metadata will persist via their stewardship independent of our own within-project data portal. 






